# POST http://localhost:5083/api/auth/login
# Content-Type: application/json

# {
#     "email": "erandesamadhan2003@gmail.com",
#     "password": "admin@1234#"
# }



POST http://localhost:5083/api/auth/verify-otp
Content-Type: application/json

{
    "email": "erandesamadhan2003@gmail.com",
    "otp": "681082"
}