export const ROUTES = {
  login: '/login',
  verifyOtp: '/verify-otp',
  dashboard: '/',
  memberSections: '/member-sections',
  memberSectionCreate: '/member-sections/create',
  memberSectionEdit: (id: number | string) => `/member-sections/${id}/edit`,
  memberTowns: '/member-towns',
  memberTownCreate: '/member-towns/create',
  memberTownEdit: (id: number | string) => `/member-towns/${id}/edit`,
  memberCenters: '/member-centers',
  memberCenterCreate: '/member-centers/create',
  memberCenterEdit: (id: number | string) => `/member-centers/${id}/edit`,
  members: '/members',
  memberCreate: '/members/create',
  memberDetail: (id: number | string) => `/members/${id}`,
  memberEdit: (id: number | string) => `/members/${id}/edit`,
  documents: '/documents',
  documentCreate: '/documents/create',
  documentEdit: (id: number | string) => `/documents/${id}/edit`,
  users: '/admin/users',
  roles: '/admin/roles',
  permissions: '/admin/permissions',
  settings: '/settings',
  memberSubTowns: '/master-data/sub-towns'
} as const
